### ISSUE TITLE
Fails to Resolve Modules from 'main' Field in package.json

### ISSUE THREAD

**Issue by Stan-Stani** [gabotechs/dep-tree#60]
I've discovered an issue with resolving modules that use the 'main' field in package.json to specify the entry point.

In my project, I have a structure where the directory "/subFile" contains a "subFile.tsx" file and a package.json file. The package.json file specifies the main field as subFile.tsx.

```json
{
  "main": "subFile.tsx"
}
```
When I import this module with `import subFile from './subFile'`, the expected behavior is that Node.js and TypeScript will look for a package.json in the subFile directory and use the file specified in the main field.

However, those files don't show up in the dependency graph.

Please consider adding support for resolving the main field in package.json files.

**Comment by gabotechs** [comment]
Thank you for reporting this!

It's definitely something that should be supported, I'll tackle this soon

**Comment by gabotechs** [comment]
I've just released a fix for this under the `0.17.7` tag. I've added some tests for ensuring this, but I don't have a real codebase that uses this feature for verifying that the released version completely solves the issue.

Could you please try it out and see if you find any problem?

**Comment by Stan-Stani** [comment]
Definitely. It'll be Monday when I get back to work!

**Comment by Stan-Stani** [comment]
Looks good! (Apart from showing how tightly coupled we are... 😅) 
![image](https://github.com/gabotechs/dep-tree/assets/14880397/62125b5f-5071-44e1-bd75-e4c4e73a13f9)
