### ISSUE TITLE
feature request: build graph using directory path

### ISSUE THREAD

**Issue by skonik** [gabotechs/dep-tree#62]
Hello. I really like the idea!
 
Is it possible to build graph using directory path? You will need to iterate over all files and all directories in specified dir, I guess. Would be really cool to analyze the whole repository and check condition of the whole code specifing only directory

**Comment by gabotechs** [comment]
Hello!

It's a good idea, I'm just deferring that as it is technically a bit complex, but it's definitely possible and would be nice to have it actually.

Stay tuned as I would probably give it a shot to this soon.

**Comment by gabotechs** [comment]
It's supported now, you can pass as many arguments as you want to the `dep-tree` command:
```shell
dep-tree your/folder/file1.js your/folder/file2.js your/folder/file3.js ...
```
or let your shell expand the files in a directory using globstars
```shell
dep-tree your/folder/*.js
```
or let your shell recursively expand everything within a dir (only some shells support this)
```shell
dep-tree your/folder/**/*.js
```
