### ISSUE TITLE
[improvement] Run directly dep-tree via npx

### ISSUE THREAD

**Issue by maxlerebourg** [gabotechs/dep-tree#72]
To avoid having `dep-tree` inside our dependencies, try to deploy it and have a global script associated.
https://github.com/Haimantika/introduction-npm-package to know how to do it.

**Comment by gabotechs** [comment]
will look into this, thanks!

**Comment by gabotechs** [comment]
I've looked into it and it's actually possible right now, but the package in npm is not called just `dep-tree` (the name was chosen), it's called `@dep-tree/cli`, so you can run it using it's npm package name:

```shell
npx @dep-tree/cli
```
