### ISSUE TITLE
How to run the command with config file?

### ISSUE THREAD

**Issue by qcgm1978** [gabotechs/dep-tree#73]
I run the command `dep-tree -c .dep-tree.yml` but it doesn't work. Prompt me `Error: requires at least 1 arg(s), only received 0` What's the key point is I missed?
```yml
# .dep-tree.yml
  entrypoints:
    - src/main.js
    - src/renderer.js
```

**Comment by gabotechs** [comment]
currently the `entrypoints` declared in the config file are ignored while rendering the graph, they are just used for the `check` functionality, so dep-tree is expecting you to pass them as arguments:

`dep-tree src/main.js src/renderer.js`

It feels inconsistent though, it makes sense that the `entrypoints` field in `.dep-tree.yml` is also taken into account for rendering the graph. I will leave this open until/if it's decided that it should work that way.

**Comment by qcgm1978** [comment]
Thanks. Now I can run it successfully.

**Comment by gabotechs** [comment]
`entrypoints` is now only an attribute inside the `check` functionality, so the top level `entrypoints` is no longer supported, now it should be:
```yaml
check:
  entrypoints:
    - my_entrypoint.file
```
Closing as no longer relevant
