### ISSUE TITLE
Support alias in code

### ISSUE THREAD

**Issue by winnieBear** [gabotechs/dep-tree#85]
First of all, thank you very much for this amazing tool, but in the process of using , I found the ts code which uses `alias` or `path alias`, neither the generated dependency tree nor the entropy diagram, there are none of these alias dependent resource files, such as:
// src/index.ts
import { environment } from '@environment';
import '@/a/b/c';

// tsconfig.json
"paths": {
    "@/*": ["./src/*"],
     "@environment": ["./src/environments/environments.ts"
].

the dependencies of src/index.ts does not have the `environment` or the `@/a/b/c`

**Comment by gabotechs** [comment]
Thanks for pointing that out! this should be easy to fix, stay tuned

**Comment by gabotechs** [comment]
I'm trying to replicate the issue but it seems to be working fine. Can you provide more info about your setup? I would be interested in knowing the full `tsconfig.json`, where your source files are located, and anything else you can provide that can help reproduce the issue.
