### ISSUE TITLE
404 for `https://dep-tree-explorer.vercel.app/`

### ISSUE THREAD

**Issue by chenrui333** [gabotechs/dep-tree#95]
looks like `https://dep-tree-explorer.vercel.app/` site is dead, raise an issue for awareness.

https://github.com/Homebrew/homebrew-core/pull/174419

**Comment by gabotechs** [comment]
That's true, that site is no longer available, the new one should be just the repo url as shown in https://github.com/Homebrew/homebrew-core/pull/174419, so it's good to go
